backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "contenido"
    label: "Contenido del sitio"
    files:
      - file: "data/combos.yml"
        label: "Combos y Proyectos"
        name: "combos"
        fields:
          - label: "Combos"
            name: "combos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Imagen", name: "imagen", widget: "image" }
          - label: "Trabajos"
            name: "trabajos"
            widget: "list"
            fields:
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Imagen", name: "imagen", widget: "image" }
